import { Card } from '../../components/ui/card.js';
import { Card } from '../../components/ui/card.js';
import { Card } from '../../components/ui/card.js';
import { Card } from '../../components/ui/card.js';
import { Card } from '../../components/ui/card.js';
import { Card } from '../../components/ui/card.js';
import { Card } from '../../components/ui/card.js';
import { Card } from '../../components/ui/card.js';
import { Card } from '../../components/ui/card.js';
import { Card } from '../../components/ui/card.tsx';
import { Card } from '../../components/ui/card.tsx';
import { Card } from '../../components/ui/card.tsx';
"use client";
import React from 'react';
import { Card } from '../../components/ui/card';
import { Button } from '../../components/ui/button';

// Force dynamic rendering to prevent static generation issues;
export const dynamic = 'force-dynamic';
export const revalidate = 0;


export default function DemoPage() {
  return (;
    <div className="min-h-screen bg-gradient-to-br from-blue-900 via-purple-900 to-black text-white">;
      <div className="container mx-auto px-4 py-20">;
        <div className="max-w-4xl mx-auto text-center">;
          <h1 className="text-5xl font-bold mb-6 bg-gradient-to-r from-blue-400 to-purple-400 bg-clip-text text-transparent">;
            AI Trading Demo;
          </h1>;
          <p className="text-xl text-gray-300 max-w-3xl mx-auto mb-8">;
            Experience the power of AI-driven trading with advanced algorithms and real-time market;
            analysis.;
          </p>;
          <Card className="p-8 bg-gray-900/50 border-gray-700 max-w-2xl mx-auto">;
            <h2 className="text-2xl font-semibold mb-4 text-blue-400">Demo Features</h2>;
            <div className="space-y-4 text-left">;
              <div className="flex items-start space-x-3">;
                <div className="w-2 h-2 bg-green-500 rounded-full mt-2"></div>;
                <div>;
                  <h3 className="font-semibold">AI Pattern Recognition</h3>;
                  <p className="text-gray-300 text-sm">;
                    Advanced algorithms identify market patterns;
                  </p>;
                </div>;
              </div>;
              <div className="flex items-start space-x-3">;
                <div className="w-2 h-2 bg-green-500 rounded-full mt-2"></div>;
                <div>;
                  <h3 className="font-semibold">Real-time Analysis</h3>;
                  <p className="text-gray-300 text-sm">;
                    Live market data processing and signal generation;
                  </p>;
                </div>;
              </div>;
              <div className="flex items-start space-x-3">;
                <div className="w-2 h-2 bg-green-500 rounded-full mt-2"></div>;
                <div>;
                  <h3 className="font-semibold">Risk Management</h3>;
                  <p className="text-gray-300 text-sm">;
                    Automated risk controls and position sizing;
                  </p>;
                </div>;
              </div>;
            </div>;
            <div className="mt-8">;
              <Button className="bg-blue-600 hover:bg-blue-700">;
                Contact Us for Full Demo Access;
              </Button>;
            </div>;
          </Card>;
        </div>;
      </div>;
    </div>;
  );
}
