# AlphaAI StockX - Netlify Configuration
[build]
  publish = ".next"
  command = "npm install && npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "10"
  NEXT_TELEMETRY_DISABLED = "1"

# Use NPM instead of PNPM for Netlify reliability
[build.processing]
  skip_processing = false

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Next.js rewrites
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
