# AlphaAI StockX - Netlify Configuration (PNPM + NPM Support)
[build]
  publish = ".next"
  command = "pnpm install --frozen-lockfile --prod=false && pnpm build"

[build.environment]
  NODE_VERSION = "18"
  PNPM_VERSION = "8"
  NEXT_TELEMETRY_DISABLED = "1"
  CI = "true"

# Fallback build command if PNPM fails
[context.production.build]
  command = "pnpm install --frozen-lockfile --prod=false && pnpm build || npm install && npm run build"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache optimization
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Next.js rewrites
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
