[build]
  command = "npm run build"
  publish = "out"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18.19.0"
  NPM_VERSION = "10.2.3"

# Enable Next.js Static HTML Export
[[plugins]]
  package = "@netlify/plugin-nextjs"

[dev]
  command = "npm run dev"
  port = 3000
  publish = "out"
