[phases.install]
cmds = ["pnpm install --frozen-lockfile --prod=false"]

[phases.build]
cmds = ["pnpm build"]

[start]
cmd = "pnpm start"

[variables]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"
PNPM_HOME = "/app/.pnpm"
PATH = "$PNPM_HOME:$PATH"
