ignoredBuiltDependencies:
  - '@tailwindcss/oxide'
  - '@prisma/client'
  - '@prisma/engines'
  - '@tensorflow/tfjs-node'
  - 'bcrypt'
  - 'ccxt'
  - 'core-js'
  - 'cypress'
  - 'prisma'
  - 'sharp'
onlyBuiltDependencies:
  - bcrypt
  - ccxt
