ignoredBuiltDependencies:
<<<<<<< HEAD
  - '@tailwindcss/oxide'
  - '@prisma/client'
  - '@prisma/engines'
  - '@tensorflow/tfjs-node'
  - 'bcrypt'
  - 'ccxt'
  - 'core-js'
  - 'cypress'
  - 'prisma'
  - 'sharp'
=======
  - unrs-resolver

onlyBuiltDependencies:
  - bcrypt
  - ccxt
>>>>>>> Fix: All import/export, logic, and formatting issues in AIStockTips.tsx and related UI components. Ensure strictNullChecks, Prettier, and robust production standards. Ready for deployment.
