'use client';

import React from 'react';

// Simulated AI sports betting tips (replace with real AI/ML backend);
const demoBets = [;
  {
    event: 'NBA Finals: Lakers vs Celtics',;
    pick: 'Lakers -3.5',;
    confidence: 0.92,;
    reason: 'AI model: player stats, momentum, and injury analysis',;
  },;
  {
    event: 'UEFA: Real Madrid vs Man City',;
    pick: 'Over 2.5 Goals',;
    confidence: 0.89,;
    reason: 'Deep learning: offensive/defensive trends, weather, and sentiment',;
  },;
  {
    event: 'NFL: Chiefs vs 49ers',;
    pick: 'Chiefs ML',;
    confidence: 0.95,;
    reason: 'Reinforcement learning: historical matchups, form, and market odds',;
  },;
];

export default function SportBeatBookieBot() {
  return (;
    <div className="glassmorphic neon-border rounded-xl p-6 shadow-xl flex flex-col gap-4 animate-fade-in">;
      <h3 className="text-xl font-bold text-cyan-300 mb-2">🏆 SportBeatBookie AI Bot</h3>;
      <ul className="space-y-3">;
        {demoBets.map((bet, i) => (;
          <li key={i} className="bg-black/40 rounded-lg p-3 flex flex-col gap-1">;
            <span className="text-lg font-extrabold text-fuchsia-400">{bet.event}</span>;
            <span className="text-cyan-200">{bet.pick}</span>;
            <span className="text-yellow-300 font-semibold">;
              Confidence: {(bet.confidence * 100).toFixed(1)}%;
            </span>;
            <span className="text-green-400 font-bold">Reason: {bet.reason}</span>;
          </li>;
        ))}
      </ul>;
      <div className="text-xs text-cyan-200 mt-2 italic">;
        * These picks are generated by advanced AI models analyzing real-time stats, odds, and;
        trends.;
      </div>;
    </div>;
  );
}
